- name: Install Firefox
  community.general.flatpak:
    name: '{{ _firefox_app_id }}'

- name: Check the runtime branch
  ansible.builtin.shell:
    cmd: >-
      set -o pipefail;
      flatpak list --system --app --columns=application,runtime
      | awk '$1 == "{{ _firefox_app_id }}" { split($2, a, "/"); print a[3] }'
  register: _firefox_ffmpeg_runtime_branch
  check_mode: false
  changed_when: false

- name: Install the FFmpeg runtime extension
  ansible.builtin.command:
    cmd: >-
      flatpak install --system --noninteractive flathub
      '{{ _firefox_ffmpeg_runtime_id }}//{{ _firefox_ffmpeg_runtime_branch.stdout }}'
  register: _firefox_ffmpeg_runtime_install
  changed_when: '"Installation complete." in _firefox_ffmpeg_runtime_install.stdout'

- name: Create the configuration directory
  ansible.builtin.file:
    path: '{{ _firefox_configuration_policies | ansible.builtin.dirname }}'
    state: directory

- name: Configure Firefox
  ansible.builtin.copy:
    src: '{{ _firefox_configuration_policies | ansible.builtin.basename }}'
    dest: '{{ _firefox_configuration_policies }}'
