- name: Check installed applications from the Fedora repository
  ansible.builtin.shell:
    cmd: >-
      set -o pipefail;
      flatpak list --system --app --columns origin,application
      | awk 'NR > 1 && $1 == "{{ _flatpak_fedora_remote_name }}" { print $2 }'
  register: _flatpak_fedora_apps_installed
  check_mode: false
  changed_when: false

- name: Uninstall applications from the Fedora repository
  community.general.flatpak:
    name: '{{ _flatpak_fedora_apps_installed.stdout_lines }}'
    state: absent

- name: Add Flathub repository
  community.general.flatpak_remote:
    name: '{{ _flatpak_flathub_name }}'
    flatpakrepo_url: '{{ _flatpak_flathub_url }}'
